### ISSUE TITLE
Add a function to extract the "header" information from all spectra

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsBackendTimsTof#1]
The data in a file is organized by frame -> scan. After opening a *.d* file/directory general information about frames is provided in the `@frames` slot:

```r
> head(tms@frames)
  Id      Time Polarity ScanMode MsMsType TimsId MaxIntensity SummedIntensities
1  1 0.1691925        +        0        0      0         1729            310665
2  2 0.2731517        +        0        0  16384         1522            309854
3  3 0.3780341        +        0        0  32768         1955            325021
4  4 0.4838910        +        0        0  49152         1840            338110
5  5 0.5885335        +        0        0  65536         1693            327301
6  6 0.6943719        +        0        0  81920         1890            326497
  NumScans NumPeaks MzCalibration       T1       T2 TimsCalibration
1      511     3302             1 25.72177 26.00259               1
2      511     3291             1 25.72177 26.00259               1
3      511     3400             1 25.72177 26.00259               1
4      511     3538             1 25.72177 26.00259               1
5      511     3457             1 25.72177 26.00259               1
6      511     3561             1 25.72177 26.00259               1
  PropertyGroup AccumulationTime RampTime
1             1            99.96    99.96
2             1            99.96    99.96
3             1            99.96    99.96
4             1            99.96    99.96
5             1            99.96    99.96
6             1            99.96    99.96
```

A simple `.header` function could thus:
- open the file with `OpenTIMS` (this will also read the general information shown above).
- extract the data from the `@frames` slot.

Open question:
- keep only data on *frames*, not the actual scans/spectra?
- maybe keep only the frame index and scan index in memory and retrieve everything else on the fly?

**Comment by cpanse** [comment]
worth reading before coding:

* https://github.com/MannLabs/alphapept/blob/master/alphapept/ext/bruker/tsfdata.py
* https://github.com/MannLabs/alphapept/blob/master/alphapept/ext/bruker/timsdata.py
* [AlphaTims: Indexing Trapped Ion Mobility Spectrometry–TOF Data for Fast and Easy Accession and Visualization](https://doi.org/10.1016/j.mcpro.2021.100149)
