### ISSUE TITLE
backendInitialize reads data and drops empty spectra

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsBackendTimsTof#14]
Currently we read the `@frames` info from the data files which provides the number of spectra per frame. In fact, many spectra (scans) are empty and no peak data nor `inv_ion_mobility` can be extracted from those. I would thus suggest the following:

- `backendInitialize` reads the `@frames` as currently done
- in addition, the `opentimsr::query` is used to get the `inv_ion_mobility` variable from each file.
- only scans (spectra) with available `inv_ion_mobility` are kept (i.e. their file, frame and scan id/index is stored in the `@indices` slot).

In the current approach the `@indices` are created based on the `@frames` slot only, which lists the number of frames per file as well as the number of spectra (scans) per frame - this number of scans is however much larger than there are scans with actual data (peaks) in the file. Thus, the new approach would remove these empty scans already from the start.

I think that might simplify quite some code avoiding to handle and create empty data for empty spectra. Any thought or objections @andreavicini @chufz?

**Comment by andreavicini** [comment]
I think it's a very good idea and simplifies things!  The only doubt is in general there can be non empty spectra with no associated `inv_ion_mobility` available in a TimsTOF file? I guess not otherwise maybe we would drop non empty spectra

**Comment by jorainer** [comment]
good point. I will simply use `query(tms, columns = c("frame", "scan"))` for all frames. That way we should get the indices of all scans.
